version: "3.7"
services:
  backend:
    build: ./backend
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate --run-syncdb
      && python manage.py loaddata fixtures.json
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    container_name: backend
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/code/src
